%% digitize_h2_curve.m
%
% Digitizes the H2 (BLACK, target-gas) curve from the GMV-2021B datasheet
% Fig.3 sensitivity plot. NOT the magenta curve this time -- on this
% chart magenta is CH4 (a cross-sensitivity curve), and H2 itself is
% plotted black. Verify against your own image's legend before clicking;
% don't assume color conventions carry over between datasheets.
%
% X axis (gas concentration, ppm): LOG scale, 0.1 -> 1000  (4 decades,
%   one more than the H2S chart's 1 -> 1000)
% Y axis (Rs/R0): LOG scale, 0.01 -> 1.0  (2 decades, one more than the
%   H2S chart's 0.1 -> 1.0 -- don't reuse the old Y_CAL_VALUES)

clear; clc; close all;

%% ---- USER SETTINGS ----
IMG_PATH = "C:\Users\sayal\OneDrive\Pictures\Screenshots\Screenshot 2026-09-26 125219.png";

X_CAL_VALUES = [0.1, 100000];   % pick the two clearest labeled gridlines in YOUR screenshot
Y_CAL_VALUES = [0.01, 10];   % same -- adjust to whichever gridlines you can click precisely

%% ---- STEP 1: Load image and calibrate axes ----
img = imread(IMG_PATH);
figure('Name','Axis Calibration','NumberTitle','off');
imshow(img); hold on;
title({'STEP 1: Click 2 points on the X axis gridlines', ...
       sprintf('in order: ppm = %g, then ppm = %g', X_CAL_VALUES(1), X_CAL_VALUES(2))}, ...
       'Interpreter','none');

fprintf('Click the X=%.1f gridline, then the X=%.0f gridline...\n', X_CAL_VALUES(1), X_CAL_VALUES(2));
[xpix_cal, ~] = ginput(2);

title({'STEP 1 (cont.): Click 2 points on the Y axis gridlines', ...
       sprintf('in order: Rs/R0 = %g, then Rs/R0 = %g', Y_CAL_VALUES(1), Y_CAL_VALUES(2))});
fprintf('Click the Y=%.2f gridline, then the Y=%.1f gridline...\n', Y_CAL_VALUES(1), Y_CAL_VALUES(2));
[~, ypix_cal] = ginput(2);

logx_cal = log10(X_CAL_VALUES);
px2logx = polyfit(xpix_cal, logx_cal, 1);

logy_cal = log10(Y_CAL_VALUES);
py2logy = polyfit(ypix_cal, logy_cal, 1);

%% ---- STEP 2: Click the H2 (BLACK) curve markers, left to right ----
title({'STEP 2: Click each BLACK marker on the H2 curve', ...
       '(NOT magenta -- magenta is CH4 on this chart)', ...
       'left to right, then press ENTER when done'});
fprintf('Click each BLACK H2 marker, left to right. Press ENTER when finished.\n');
[xpix_pts, ypix_pts] = ginput;

ppm_digitized  = 10 .^ polyval(px2logx, xpix_pts);
rsr0_digitized = 10 .^ polyval(py2logy, ypix_pts);

[ppm_digitized, sortIdx] = sort(ppm_digitized);
rsr0_digitized = rsr0_digitized(sortIdx);

fprintf('\nDigitized points (ppm, Rs/R0):\n');
disp([ppm_digitized, rsr0_digitized]);

%% ---- STEP 3: Fit a curve, check R^2 before trusting it ----
logppm = log10(ppm_digitized);
logrsr0 = log10(rsr0_digitized);
p = polyfit(logppm, logrsr0, 1);
b = p(1);
a = 10^p(2);
fprintf('\nFitted power law: Rs/R0 = %.5f * ppm^(%.5f)\n', a, b);

rsr0_fit_at_pts = a .* ppm_digitized .^ b;
ss_res = sum((rsr0_digitized - rsr0_fit_at_pts).^2);
ss_tot = sum((rsr0_digitized - mean(rsr0_digitized)).^2);
r2 = 1 - ss_res/ss_tot;
fprintf('Fit R^2 = %.5f\n', r2);
% Your H2S curve needed piecewise interpolation because a single power
% law under/overshot at the ends -- check this R^2 and eyeball the plot
% in Step 5 before assuming a single power law is good enough here too.
% If it's not, use the raw digitized points directly (same piecewise
% log-log interpolation pattern as H2S::ratioToPPM), not this global fit.

%% ---- STEP 4: Build a 256-row lookup table ----
N = 256;
rsr0_min = min(rsr0_digitized);
rsr0_max = max(rsr0_digitized);
rsr0_lut = linspace(rsr0_min, rsr0_max, N)';
ppm_lut = (rsr0_lut ./ a) .^ (1/b);

fprintf('\nNew lookup table spans Rs/R0 = %.4f to %.4f, ppm = %.2f to %.2f\n', ...
    rsr0_lut(1), rsr0_lut(end), ppm_lut(1), ppm_lut(end));

%% ---- STEP 5: Plot (no existing-table comparison for H2 yet) ----
figure('Name','New H2 LUT','NumberTitle','off');
plot(ppm_digitized, rsr0_digitized, 'ks', 'MarkerFaceColor','k', 'DisplayName','Digitized points'); hold on;
plot(ppm_lut, rsr0_lut, 'k-', 'LineWidth', 1.5, 'DisplayName','Fitted LUT');
set(gca, 'XScale', 'log', 'YScale', 'log');
xlabel('gas concentration (ppm)'); ylabel('Rs/R0');
legend('Location','northeast');
title('Digitized H2 curve and fitted lookup table');
grid on;

%% ---- STEP 6: Export as a C array ----
fid = fopen('lookup_H2_new.c', 'w');
fprintf(fid, '// Auto-generated by digitize_h2_curve.m\n');
fprintf(fid, '// Fit: Rs/R0 = %.6f * ppm^(%.6f), R^2 = %.5f\n\n', a, b, r2);
fprintf(fid, 'const Lookup_t_H2 lookup_H2_new[%d] = {\n', N);
for i = 1:N
    fprintf(fid, '    {%.6f, {%.0f}},\n', rsr0_lut(i), round(ppm_lut(i)*10));
end
fprintf(fid, '};\n');
fclose(fid);
fprintf('\nWrote lookup_H2_new.c (ppm values x10 fixed-point)\n');